apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: memuser-monitor
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
  selector:
    matchLabels:
      app: memuser
