---
apiVersion: batch/v1
kind: Job
metadata:
    generateName: work-queue
spec:
    template:
        spec:
            containers:
            - name: work
              image: busybox
              command: ["sleep", "300"]
              resources:
                requests:
                    memory: 500Mi
                    cpu: 250m
            restartPolicy: Never
            nodeSelector:
                spotInstance: "true"
    backoffLimit: 4
    completions: 50
    parallelism: 50